### ISSUE TITLE
저장소 첫 접속 시 보여줄 사용자 성공 스토리 개발

### ISSUE THREAD

**Issue by map4free** [map4free/maps4k-freelancer#18]
마케터로서 사용자에게 제품을 사용하면 무엇이 좋은지 쉽게 전달할 수 있는 사용자 스토리를 제공한다.
그래서
- 사용자가 프로젝트를 통해 어떤 불편이 개선되고 어떤 이익을 취할 수 있는지 쉽게 안다.
- 사용자가 자신의 이익을 위해 정보를 제공하는 것에 동기부여한다.

### 수용 조건

- [x] 사용자 성공 스토리 참조자료를 읽고 정리한다.
- [x] 초안 작성 및 
- [ ] 소규모 공개 & 피드백 받기
- [ ] 초기 피드백 반영한 사용자 성공 스토리를 완성

### 참조 자료

- [사용자 성공 스토리 템플릿](https://magneticspeaking.com/the-ultimate-customer-success-story-template-formula/)
- [팔리는 스토리를 말해라: 베스트 사용자 성공 스토리 템플릿](https://www.skeletonproductions.com/insights/customer-success-story-template)

**Comment by map4free** [comment]
원문 : [즉시 배울 수있는 고객 성공 스토리 예시](https://www.skeletonproductions.com/insights/customer-success-story-examples)

**Comment by map4free** [comment]
원문 : [팔릴 이야기를 말하라: 베스트 고객 성공 스토리 양식](https://www.skeletonproductions.com/insights/customer-success-story-template)

**Comment by map4free** [comment]
IT프리 단가 전선(이하 아단전)은 일을 구할 때 수월하게 계약을 하고 싶은 사람들이 서로 모인 집단입니다. 아단전은 프리랜서가 업체와 계약할 때 충분한 정보를 가짐으로써 계약의 손해를 줄일 수 있어야 한다고 생각합니다. 아단전의 목표는 프리랜서가 업체와 계약 시 가장 도움이 될 정보를 제공하는 것입니다.

프래랜서들이 서로 계약한 단가 정보의 평균을 보여줌으로써 업체와 단가 협상 시 참조할 수 있는 '단가 후려치기' 지지선을 제공합니다.

**Comment by map4free** [comment]
## 피드백 

내용 : 모든 기계 제품을 애플만 쓰는 거 같은 외국인 번역말투다.

IT 프리랜서 단가 전선(이하 ‘아단전’)은 일을 구할 때 업체와의 계약을 보다 수월하게 하고 싶은 사람들이 모인 집단입니다. 아단전은 프리랜서가 계약에 관련된 충분한 정보를 가짐으로써 업체와 계약할 때 손해를 줄일 수 있어야 한다고 생각합니다. 아단전의 목표는 프리랜서가 업체와의 계약 시 가장 도움이 될 정보를 제공하는 것입니다.

아단전은 업체와 프리랜서 간의 계약 관련 정보 균형에 대해 고민하고 있었습니다. 여러 업체에 전화를 걸어 문의를 하거나 주변 지인들에게 물어보기도 했지만, 업체별로 공개하는 정보의 범위가 달랐고, 주변 지인들의 경험도 제각각이었습니다. 혼자서는 정보력을 갖추기에 한계가 있었습니다. 결국 업체와의 계약 앞에서 홀로 애쓰는 모든 개인의 정보 공유와 연대가 필요해졌습니다.

아단전 DB(가칭)는 각각의 프리랜서가 경험한 계약 정보를 한 곳으로 모아, 한 사람 몫의 기여를 통해 집단의 경험을 누릴 수 있게 합니다. 이 DB를 통해 프리랜서는 업체에서 제시 받은 계약 조건이 다른 프리랜서들의 경험 평균치보다 좋지 않을 경우, 업체를 피하거나 최소한의 보장 조건을 요구할 수 있게 됩니다.

아단전 DB(가칭)에 참여함으로써 업체가 제시한 조건이 얼마나 낙후한지 알지 못하고 계약을 맺을 수밖에 없었던 일(예, 단가 후려치기)을 예방하거나 피할 수 있을 것입니다.

더 나아가, 업체들의 악덕 계약 체결률이 낮아지고, 불합리한 처우를 받는 개인이 줄어들며, IT 업계의 업체들이 제시하는 최소한의 계약 조건이 개선되기를 바랍니다.

**Comment by tool4Free** [comment]
## 일부 수정

아단전은 하청업체와 프리랜서와의 계약 관련 정보 균형을 위해 고민하고 있었습니다. 이를 위해 개인적으로 업체나 주변인들에게 정보를 구해봤지만, 하청업체마다 말이 다르고 주변인들의 말도 제각각이라 매번 일을 구할 때마다 업체가 하는 말에 휘둘릴 수 밖에 없었습니다. 결국 혼자 파악할 수 있는 정보로는 업체와의 균형을 이룰 수 없습니다. 하청업체 앞에서 홀로 애쓰는 모든 개인들의 힘의 연결이 필요합니다.

아단전은 각각의 프리랜서가 경험한 계약정보를 한 곳으로 모으도록 해, 개인의 몫만큼 기여하고 집단의 경험을 공유할 수 있게 합니다. 아단전을 통해 프리랜서는 업체에게 제시받은 조건이나 일이 다른 사람의 평균적인 경험보다 안 좋을 경우 업체를 피하거나 최소 조건을 요구할 수 있게 됩니다.
