### ISSUE TITLE
깃헙에서 flagged 되고 spam 계정 처리된 것 풀기

### ISSUE THREAD

**Issue by ghost** [map4free/maps4k-freelancer#8]
왜인지 모르겠다.

### 수용 조건

- [x] 깃헙에 오류사항에 관한 메일을 보낸다.
- [x] 왜 그런지 알아낸다
- [x] 해결책을 적용한다.

**Comment by map4free** [comment]
They flagged his account off. 
And I'm the owner now.

**Comment by map4free** [comment]
I don't know why, but some error happened.
It's slow & sometimes profile picture now show up. but woking.
